### ISSUE TITLE
Publish project via `pypi`

### ISSUE THREAD

**Issue by writememe** [writememe/rat_hunter#33]
# Summary

Investigate packaging the project, so it's available via pip/pypi

## To-do list

- [ ] Setup `MANIFEST.in` file (https://github.com/writememe/motherstarter/blob/master/MANIFEST.in)
- [ ] Setup `setup.py` file (https://github.com/writememe/motherstarter/blob/master/setup.py)
- [ ] Setup `version` and `author` configurations (https://github.com/writememe/motherstarter/blob/master/motherstarter/__init__.py)
- [ ] Look at Github actions for publish to pypi (https://github.com/writememe/motherstarter/blob/master/.github/workflows/publish.yaml)

## Things to investigate

Almost certain I don't want to build a CLI for this tool, so need to work out how to package an app that doesn't have a CLI
